### ISSUE TITLE
Cannot seem to get sortTailwindcssClasses working in VSCode

### ISSUE THREAD

**Issue by Swennet** [shufo/prettier-plugin-blade#161] opened 2022-11-14 14:49 UTC
I cannot seem to get the Tailwindcss auto sorting working in VSCode. On save it does seem to use the prettier-plugin-blade package.

I'm testing this by juggling some Tailwind classes in my blade template into a random order. What am I doing wrong?

```
{
	"semi": true,
	"singleQuote": true,
	"trailingComma": "es5",
	"printWidth": 150,
	"useTabs": true,
	"tabWidth": 1,
	"plugins": ["@shufo/prettier-plugin-blade"],
	"overrides": [
		{
			"files": ["*.blade.php"],
			"options": {
				"parser": "blade",
				"printWidth": 999,
				"sortTailwindcssClasses": true,
				"wrapAttributes": "auto",
				"sortHtmlAttributes": "none",
				"noPhpSyntaxCheck": false
			}
		}
	]
}
```

Saving a .blade.php file

```["INFO" - 3:47:23 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:47:23 PM] Prettier Options:
{
  "filepath": "/mypath/resources/views/vp-account-settings.blade.php",
  "parser": "blade",
  "useTabs": true,
  "tabWidth": 1,
  "endOfLine": "lf",
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "printWidth": 999,
  "plugins": [
    "/mypath/node_modules/@shufo/prettier-plugin-blade/dist/index.js"
  ],
  "sortTailwindcssClasses": true,
  "wrapAttributes": "auto",
  "sortHtmlAttributes": "none",
  "noPhpSyntaxCheck": false
}
["INFO" - 3:47:23 PM] Formatting completed in 139ms.```

**Comment by shufo** [comment] 2022-11-24 04:09
Thanks for creating the issue.
I'll look into it.

**Comment by gabrieldasilva** [comment] 2022-12-04 23:20
Having the same issue here. Suddenly sorting stopped working. 

The only change I can relate is updating libraries (including this one from 1.8.0 to 1.8.1).

**Comment by yabdab** [comment] 2022-12-05 16:05
Same here. Everything else works, but the TW classes stopped sorting.
I am using Nova IDE from Panic fyi.

**Comment by yabdab** [comment] 2022-12-08 13:05
Looks like it may still work in css and scss files, but not blade.php files?

**Comment by yabdab** [comment] 2022-12-08 13:13
Maybe related to this?
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/52

**Comment by Blinks44** [comment] 2022-12-09 10:35
Fresh project in PHPStorm also stopped to sort tailwind classes. Everything from plugin works, except sorting.

**Comment by Blinks44** [comment] 2022-12-09 11:49
@shufo 
Fresh install laravel with only blade-prettier plugin. Everything works, even sorting my classes with tailwind classes, but not tailwind classes order (tried version 1.7 and 1.8 of blade-prettier):

![Recording 2022-12-09 at 14 45 38](https://user-images.githubusercontent.com/8570193/206695987-f3c71efe-73ba-4d2b-bc84-fe396977f1a7.gif)

**Comment by yabdab** [comment] 2022-12-13 11:16
Any progress in this?

**Comment by shufo** [comment] 2022-12-29 05:15
Sorry for late reply. I've been a little busy lately.
And thanks for the report.

I tried reproduced it today and seems working in my environment.

- VSCode 1.74.2
- prettier-vscode 9.10.3
- prettier-plugin-blade 1.8.3

https://user-images.githubusercontent.com/1641039/209903782-828a330d-14ba-4ccb-8887-b34f22c15d30.mp4

I remember reproduced this bug at https://github.com/shufo/prettier-plugin-blade/issues/161#issuecomment-1325931973, but for some reason I can't reproduce it now.

Is this bug still occurring in your environment? If it does not occur, upstream prettier-vscode or vscode may be the cause. Because I didn't touch around tailwind sort feature recently.

**Comment by Blinks44** [comment] 2022-12-29 09:28
> Is this bug still occurring in your environment? If it does not occur, upstream prettier-vscode or vscode may be the cause. Because I didn't touch around tailwind sort feature recently.

In PHPStorm sorting still doesn't work. Everything from plugin works, except sorting tailwind classes.

Enviroment:

- PHPStorm 2022.3.1
- Built in prettier
- prettier-plugin-blade 1.8.3

One months ago everything works fine, but not now :(

**Comment by yabdab** [comment] 2022-12-29 11:58
Using the following with Nova. Still not working?

@shufo/prettier-plugin-blade@1.8.3
prettier-plugin-tailwindcss@0.2.1
prettier@2.8.1

One thing I did notice, is it does place non-tailwind classes first, but tailwind classes do not sort correctly.

It does sort on .css and .scss files, but does not work on php and .blade files anymore. ☹️

**Comment by Blinks44** [comment] 2022-12-29 12:08
> Using the following with Nova. Still not working?
> 
> @shufo/prettier-plugin-blade@1.8.3 prettier-plugin-tailwindcss@0.2.1 prettier@2.8.1
> 
> One thing I did notice, is it does place non-tailwind classes first, but tailwind classes do not sort correctly.
> 
> It does sort on .css and .scss files, but does not work on php and .blade files anymore. ☹️

Yep, absolutely the same in PHPStorm.

**Comment by wsamoht** [comment] 2022-12-30 20:03
> One thing I did notice, is it does place non-tailwind classes first, but tailwind classes do not sort correctly.

This is my experience as well. @shufo, your video is showing custom classes and Tailwind classes being sorted (custom classes before Tailwind classes). Try reproducing with just Tailwind classes.

**Comment by beebmx** [comment] 2023-01-04 15:58
> > Using the following with Nova. Still not working?
> > @shufo/prettier-plugin-blade@1.8.3 prettier-plugin-tailwindcss@0.2.1 prettier@2.8.1
> > One thing I did notice, is it does place non-tailwind classes first, but tailwind classes do not sort correctly.
> > It does sort on .css and .scss files, but does not work on php and .blade files anymore. ☹️
> 
> Yep, absolutely the same in PHPStorm.

Same here with PHPStorm with @shufo/prettier-plugin-blade@1.8.4

**Comment by yabdab** [comment] 2023-01-04 16:00
Is this something we gotta live with, or are there plans to fix?

**Comment by shufo** [comment] 2023-01-08 10:38
@wsamoht 
It also seems works as expected with just tailwindcss classes.

https://user-images.githubusercontent.com/1641039/211191198-4a0c4567-79ac-4691-aec6-21c431c79a6c.mp4

This is the same sort as [Official plugin](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#:~:text=%3Cbutton%20class%3D%22bg%2Dsky%2D700%20px%2D4%20py%2D2%20text%2Dwhite%20hover%3Abg%2Dsky%2D800%20sm%3Apx%2D8%20sm%3Apy%2D3%22%3E...%3C/button%3E
).

There may be other causes, but I can't reproduce them. 
Can you reproduce it with VSCode? If it cannot be reproduced, it may be a problem specific to PHPStorm or other plugins.

**Comment by ctoma** [comment] 2023-01-09 12:38
I have the same issue the others have mentioned, but with PHPStorm. To eliminate PHPStorm as the cause I have been trying to get it working just using the CLI, but this yields the same behavior that the others experience.

```
root@X:/blade-testing# node -v
v16.19.0
root@X:/blade-testing# ./node_modules/.bin/prettier -v
2.8.2
root@X:/blade-testing# cat resources/views/.prettierrc.json
{
    "overrides": [
        {
            "files": ["*.blade.php"],
            "options": {
                "tabWidth": 4,
                "parser": "blade"
            }
        }
    ],
    "printWidth": 120,
    "tabWidth": 4,
    "plugins": ["@shufo/prettier-plugin-blade"],
    "wrapAttributes": "auto",
    "sortTailwindcssClasses": true,
    "tailwindcssConfigPath": "tailwind.config.js",
    "sortHtmlAttributes": "none"
}
root@X:/blade-testing# cat resources/views/tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}
root@X:/blade-testing# cat resources/views/index.blade.php
<button class="text-white myclass px-4 sm:px-8 py-2 sm:py-3 bg-sky-700 hover:bg-sky-800">abc</button>
root@X:/blade-testing# ./node_modules/.bin/prettier resources/views/index.blade.php --config /blade-testing/resources/views/.prettierrc.json
<button class="myclass text-white px-4 sm:px-8 py-2 sm:py-3 bg-sky-700 hover:bg-sky-800">abc</button>
root@X:/blade-testing#
```
I have tried using pretty much every combination of prettier flags, tailwind config I can think of and am not able to get it working as expected.

**Comment by wsamoht** [comment] 2023-01-10 20:31
> It also seems works as expected with just tailwindcss classes.

@shufo I am using VSCode where it is not working. I tried the exact same classes that you did and they don't sort for me. I will try and play around with it some more to see if I can narrow it down.

**Comment by shufo** [comment] 2023-01-21 10:00
Recently I [fixed](https://github.com/shufo/tailwindcss-class-sorter/commit/8c08b53727a8ad32ca1bc7ff86b538107d24d27f) a Tailwind related bug that reproduced when I upgraded Tailwind to 3.2 and Released https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.8.6.

Can anyone try 1.8.6? After upgrading, don't forget to reload the Editor (VSCode, PHPStorm, etc...)

**Comment by yabdab** [comment] 2023-01-21 11:38
@shufo  In some limited tests I am seeing that **it is now working** in Panic's Nova editor ( for Mac ) 🎉

**Comment by wsamoht** [comment] 2023-01-21 19:56
@shufo version 1.8.6 fixed my issues in VS Code! THANK YOU!!!!!!

**Comment by Blinks44** [comment] 2023-01-22 13:05
Yep, since 1.8.6 everything works fine in PHPStorm.

You're awesome @shufo !

**Comment by shufo** [comment] 2023-01-22 17:20
It seems to be fixed in every editor, so I'm going to close this issue.

**Closed by shufo** 2023-01-22 17:20 UTC
